/**
 * @generated by @app/core:setup
 * @generatedAt 2024-01-15T10:00:00Z
 * 
 * Common validation schemas - Reusable patterns
 */

import { createFileMetadata } from '@app/tools/file-marker/marker';
import { z } from 'zod';

export const __metadata = createFileMetadata('@app/core:setup');

/**
 * Common patterns for reuse
 */
export const common = {
  // IDs
  id: z.string().cuid(),
  uuid: z.string().uuid(),
  
  // Strings
  email: z.string().email(),
  url: z.string().url(),
  nonEmptyString: z.string().min(1),
  slug: z.string().regex(/^[a-z0-9-]+$/),
  
  // Numbers
  positiveInt: z.number().int().positive(),
  positiveNumber: z.number().positive(),
  percentage: z.number().min(0).max(100),
  
  // Dates
  dateString: z.string().datetime(),
  futureDate: z.date().refine((date) => date > new Date(), {
    message: 'Date must be in the future',
  }),
  
  // Arrays
  nonEmptyArray: <T extends z.ZodTypeAny>(schema: T) =>
    z.array(schema).min(1),
  uniqueArray: <T extends z.ZodTypeAny>(schema: T) =>
    z.array(schema).refine((arr) => new Set(arr).size === arr.length, {
      message: 'Array must contain unique values',
    }),
};

/**
 * Pagination schemas
 */
export const cursorPaginationSchema = z.object({
  cursor: z.string().optional(),
  limit: z.number().min(1).max(100).default(20),
});

export const offsetPaginationSchema = z.object({
  page: z.number().min(1).default(1),
  limit: z.number().min(1).max(100).default(20),
});

/**
 * Sort schema
 */
export const sortSchema = z.object({
  field: z.string(),
  direction: z.enum(['asc', 'desc']).default('asc'),
});
