/**
 * @generated by @app/core:setup
 * @generatedAt 2024-01-15T10:00:00Z
 * 
 * Validation package - Centralized Zod schemas
 * 
 * ✅ CORRECT: import { common, validate } from '@app/validation';
 * ❌ WRONG: import { z } from 'zod'; z.object(...)
 */

import { createFileMetadata } from '@app/tools/file-marker/marker';

export const __metadata = createFileMetadata('@app/core:setup');

export { common, cursorPaginationSchema, offsetPaginationSchema, sortSchema } from './common.schema';
export { validate, validateSafe } from './validate';
