/**
 * @generated by @app/core:setup
 * @generatedAt 2024-01-15T10:00:00Z
 * 
 * Validation utilities - Returns branded Validated type
 */

import { createFileMetadata } from '../../../tools/file-marker/marker';
import type { Validated } from '@app/types';
import { ValidationError } from '@app/errors';
import { logger } from '@app/logger';
import { z } from 'zod';

export const __metadata = createFileMetadata('@app/core:setup');

/**
 * Validate data with Zod schema
 * Returns Validated<T> phantom type
 * 
 * @throws ValidationError if validation fails
 */
export function validate<T>(
  schema: z.ZodSchema<T>,
  data: unknown
): Validated<T> {
  try {
    const result = schema.parse(data);
    return result as Validated<T>;
  } catch (error) {
    if (error instanceof z.ZodError) {
      logger.warn('Validation failed', {
        errors: error.errors,
        data: JSON.stringify(data),
      });
      
      throw new ValidationError('Validation failed', {
        errors: error.errors,
      });
    }
    throw error;
  }
}

/**
 * Safe validation - returns Result instead of throwing
 */
export function validateSafe<T>(
  schema: z.ZodSchema<T>,
  data: unknown
): { success: true; data: Validated<T> } | { success: false; error: z.ZodError } {
  const result = schema.safeParse(data);
  
  if (result.success) {
    return {
      success: true,
      data: result.data as Validated<T>,
    };
  }
  
  return {
    success: false,
    error: result.error,
  };
}
