/**
 * @generated by @app/core:setup
 * @generatedAt 2024-01-15T10:00:00Z
 * 
 * Logger interface - All loggers must implement this
 */

import { createFileMetadata } from '../../../tools/file-marker/marker';
import type { LogLevel } from '@app/types';

export const __metadata = createFileMetadata('@app/core:setup');

export interface LogContext {
  timestamp: Date;
  level: LogLevel;
  message: string;
  data?: unknown;
  error?: Error;
  module?: string;
}

/**
 * Logger interface
 * Swap implementation by changing factory
 */
export interface ILogger {
  error(message: string, error?: Error | unknown, data?: unknown): void;
  warn(message: string, data?: unknown): void;
  info(message: string, data?: unknown): void;
  debug(message: string, data?: unknown): void;
  setLevel(level: LogLevel): void;
}
