/**
 * @generated by @app/core:setup
 * @generatedAt 2024-01-15T10:00:00Z
 * 
 * Logger package - Centralized logging
 * 
 * ✅ CORRECT: import { logger } from '@app/logger';
 * ❌ WRONG: console.log(), import winston, import pino
 */

import { createFileMetadata } from '@app/tools/file-marker/marker';

export const __metadata = createFileMetadata('@app/core:setup');

export { logger, Logger } from './logger';
export type { ILogger, LogContext } from './interface';
