/**
 * @generated by @app/core:setup
 * @generatedAt 2024-01-15T10:00:00Z
 * 
 * Logger implementation - SINGLE INSTANCE
 */

import { createFileMetadata } from '@app/tools/file-marker/marker';
import type { ILogger, LogContext } from './interface';
import { LogLevel } from '@app/types';

export const __metadata = createFileMetadata('@app/core:setup');

class Logger implements ILogger {
  private static instance: Logger;
  private minLevel: LogLevel = LogLevel.INFO;

  private constructor() {
    // Singleton - private constructor
  }

  static getInstance(): Logger {
    if (!Logger.instance) {
      Logger.instance = new Logger();
    }
    return Logger.instance;
  }

  setLevel(level: LogLevel): void {
    this.minLevel = level;
  }

  private shouldLog(level: LogLevel): boolean {
    const levels = [LogLevel.ERROR, LogLevel.WARN, LogLevel.INFO, LogLevel.DEBUG];
    return levels.indexOf(level) <= levels.indexOf(this.minLevel);
  }

  private formatLog(context: LogContext): string {
    const { timestamp, level, message, module, data } = context;
    const moduleStr = module ? `[${module}]` : '';
    const dataStr = data ? `\n${JSON.stringify(data, null, 2)}` : '';
    return `${timestamp.toISOString()} ${level.toUpperCase()} ${moduleStr} ${message}${dataStr}`;
  }

  private getCallerModule(): string {
    const stack = new Error().stack;
    if (!stack) return 'unknown';

    const lines = stack.split('\n');
    const callerLine = lines[4] || '';
    const match = callerLine.match(/at\s+(.+?)\s+\(/);
    return match ? match[1] : 'unknown';
  }

  private log(level: LogLevel, message: string, data?: unknown, error?: Error): void {
    if (!this.shouldLog(level)) return;

    const context: LogContext = {
      timestamp: new Date(),
      level,
      message,
      data,
      error,
      module: this.getCallerModule(),
    };

    const formatted = this.formatLog(context);

    switch (level) {
      case LogLevel.ERROR:
        console.error(formatted, error || '');
        break;
      case LogLevel.WARN:
        console.warn(formatted);
        break;
      case LogLevel.INFO:
        console.info(formatted);
        break;
      case LogLevel.DEBUG:
        console.debug(formatted);
        break;
    }
  }

  error(message: string, error?: Error | unknown, data?: unknown): void {
    const errorObj = error instanceof Error ? error : undefined;
    const errorData = error instanceof Error ? data : error;
    this.log(LogLevel.ERROR, message, errorData, errorObj);
  }

  warn(message: string, data?: unknown): void {
    this.log(LogLevel.WARN, message, data);
  }

  info(message: string, data?: unknown): void {
    this.log(LogLevel.INFO, message, data);
  }

  debug(message: string, data?: unknown): void {
    this.log(LogLevel.DEBUG, message, data);
  }
}

// Export singleton instance
export const logger = Logger.getInstance();

// Export class for testing
export { Logger };
