/**
 * @generated by @app/core:setup
 * @generatedAt 2024-01-15T10:00:00Z
 * 
 * Logger implementation - Use Dependency Injection
 */

import { createFileMetadata } from '@app/tools/file-marker/marker';
import type { ILogger, LogContext } from './interface';
import { LogLevel } from '@app/types';

export const __metadata = createFileMetadata('@app/core:setup');

/**
 * Console logger implementation
 * Inject this via constructor, don't use as singleton
 */
export class ConsoleLogger implements ILogger {
  constructor(private minLevel: LogLevel = LogLevel.INFO) {}

  setLevel(level: LogLevel): void {
    this.minLevel = level;
  }

  private shouldLog(level: LogLevel): boolean {
    const levels = [LogLevel.ERROR, LogLevel.WARN, LogLevel.INFO, LogLevel.DEBUG];
    return levels.indexOf(level) <= levels.indexOf(this.minLevel);
  }

  private formatLog(level: LogLevel, message: string, context?: LogContext): void {
    const timestamp = new Date().toISOString();
    console.error(`[${timestamp}] [${level}] ${message}`, context || '');
  }

  info(message: string, context?: LogContext): void {
    if (this.shouldLog(LogLevel.INFO)) {
      this.formatLog(LogLevel.INFO, message, context);
    }
  }

  error(message: string, error?: unknown, context?: LogContext): void {
    if (this.shouldLog(LogLevel.ERROR)) {
      this.formatLog(LogLevel.ERROR, message, { ...context, error });
    }
  }

  warn(message: string, context?: LogContext): void {
    if (this.shouldLog(LogLevel.WARN)) {
      this.formatLog(LogLevel.WARN, message, context);
    }
  }

  debug(message: string, context?: LogContext): void {
    if (this.shouldLog(LogLevel.DEBUG)) {
      this.formatLog(LogLevel.DEBUG, message, context);
    }
  }
}

/**
 * Factory function for creating loggers
 * Use this in your composition root
 */
export function createLogger(level: LogLevel = LogLevel.INFO): ILogger {
  return new ConsoleLogger(level);
}
