/**
 * @generated by @app/core:setup
 * @generatedAt 2024-01-15T10:00:00Z
 * 
 * Pagination helpers - Reusable across all models
 */

import { createFileMetadata } from '@app/tools/file-marker/marker';
import { db } from './client';
import type {
  CursorPaginationInput,
  CursorPaginatedResponse,
  OffsetPaginationInput,
  OffsetPaginatedResponse,
} from '@app/types';

export const __metadata = createFileMetadata('@app/core:setup');

/**
 * Cursor-based pagination
 * Best for infinite scroll
 */
export async function cursorPaginate<T>(
  model: keyof typeof db,
  options: CursorPaginationInput & {
    where?: any;
    orderBy?: any;
    include?: any;
  }
): Promise<CursorPaginatedResponse<T>> {
  const { cursor, limit = 20, where, orderBy, include } = options;

  const items = await (db[model] as any).findMany({
    take: limit + 1,
    cursor: cursor ? { id: cursor } : undefined,
    where,
    orderBy: orderBy || { createdAt: 'desc' },
    include,
  });

  const hasMore = items.length > limit;
  const data = hasMore ? items.slice(0, -1) : items;
  const nextCursor = hasMore ? data[data.length - 1].id : null;

  return {
    data,
    nextCursor,
    hasMore,
  };
}

/**
 * Offset-based pagination
 * Best for page numbers
 */
export async function offsetPaginate<T>(
  model: keyof typeof db,
  options: OffsetPaginationInput & {
    where?: any;
    orderBy?: any;
    include?: any;
  }
): Promise<OffsetPaginatedResponse<T>> {
  const { page = 1, limit = 20, where, orderBy, include } = options;

  const [data, total] = await Promise.all([
    (db[model] as any).findMany({
      skip: (page - 1) * limit,
      take: limit,
      where,
      orderBy: orderBy || { createdAt: 'desc' },
      include,
    }),
    (db[model] as any).count({ where }),
  ]);

  return {
    data,
    pagination: {
      page,
      limit,
      total,
      totalPages: Math.ceil(total / limit),
    },
  };
}
