/**
 * @generated by @app/core:setup
 * @generatedAt 2024-01-15T10:00:00Z
 * 
 * Application constants - Single source of truth
 */

import { createFileMetadata } from '../../../tools/file-marker/marker';

export const __metadata = createFileMetadata('@app/core:setup');

/**
 * Pagination defaults
 */
export const PAGINATION = {
  DEFAULT_LIMIT: 20,
  MAX_LIMIT: 100,
  MIN_LIMIT: 1,
} as const;

/**
 * Cache TTLs (in seconds)
 */
export const CACHE_TTL = {
  SHORT: 60,        // 1 minute
  MEDIUM: 300,      // 5 minutes
  LONG: 3600,       // 1 hour
  DAY: 86400,       // 24 hours
} as const;

/**
 * Rate limiting
 */
export const RATE_LIMIT = {
  WINDOW_MS: 60000,     // 1 minute
  MAX_REQUESTS: 100,    // requests per window
} as const;

/**
 * Session
 */
export const SESSION = {
  MAX_AGE: 30 * 24 * 60 * 60, // 30 days (in seconds)
  UPDATE_AGE: 24 * 60 * 60,   // Update session every 24h
} as const;

/**
 * File upload limits
 */
export const UPLOAD = {
  MAX_SIZE: 5 * 1024 * 1024,  // 5MB
  ALLOWED_TYPES: ['image/jpeg', 'image/png', 'image/webp'],
} as const;

/**
 * Validation limits
 */
export const LIMITS = {
  MAX_STRING_LENGTH: 1000,
  MAX_ARRAY_LENGTH: 100,
  MAX_TAGS: 10,
} as const;
