/**
 * @generated by @app/core:setup
 * @generatedAt 2024-01-15T10:00:00Z
 * 
 * Authentication & authorization errors
 */

import { createFileMetadata } from '@app/tools/file-marker/marker';
import { BaseError } from './base';

export const __metadata = createFileMetadata('@app/core:setup');

export class AuthenticationError extends BaseError {
  constructor(message: string = 'Authentication required', context?: Record<string, unknown>) {
    super(message, 'UNAUTHENTICATED', 401, true, context);
  }
}

export class AuthorizationError extends BaseError {
  constructor(message: string = 'Insufficient permissions', context?: Record<string, unknown>) {
    super(message, 'FORBIDDEN', 403, true, context);
  }
}
