/**
 * @generated by @app/core:setup
 * @generatedAt 2024-01-15T10:00:00Z
 * 
 * ONE error system - Everything in one place
 */

import { createFileMetadata } from '@app/tools/file-marker/marker';

export const __metadata = createFileMetadata('@app/core:setup');

// ============================================================================
// ERROR CODES (single source of truth)
// ============================================================================

export const ErrorCode = {
  // Validation errors (400)
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_INPUT: 'INVALID_INPUT',
  
  // Not found errors (404)
  NOT_FOUND: 'NOT_FOUND',
  
  // Auth errors (401, 403)
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  FORBIDDEN: 'FORBIDDEN',
  
  // Server errors (500)
  DATABASE_ERROR: 'DATABASE_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = typeof ErrorCode[keyof typeof ErrorCode];

// ============================================================================
// ERROR MESSAGES (single source of truth)
// ============================================================================

export const ErrorMessage = {
  // Validation
  VALIDATION_ERROR: 'Validation failed',
  INVALID_INPUT: 'Invalid input provided',
  
  // Not found
  NOT_FOUND: 'Resource not found',
  
  // Auth
  UNAUTHENTICATED: 'Authentication required',
  FORBIDDEN: 'Insufficient permissions',
  
  // Server
  DATABASE_ERROR: 'Database operation failed',
  INTERNAL_ERROR: 'An unexpected error occurred',
} as const;

// ============================================================================
// ONE ERROR CLASS
// ============================================================================

export class AppError extends Error {
  constructor(
    public readonly code: ErrorCode,
    message?: string,
    public readonly statusCode: number = 500,
    public readonly context?: Record<string, unknown>
  ) {
    super(message || ErrorMessage[code] || 'An error occurred');
    this.name = 'AppError';
    Error.captureStackTrace(this, this.constructor);
  }

  toJSON() {
    return {
      code: this.code,
      message: this.message,
      statusCode: this.statusCode,
      context: this.context,
    };
  }
}

// ============================================================================
// FACTORY FUNCTIONS (convenience)
// ============================================================================

export const createError = {
  validation: (message?: string, context?: Record<string, unknown>) =>
    new AppError(ErrorCode.VALIDATION_ERROR, message, 400, context),
    
  notFound: (resource: string, id?: string) =>
    new AppError(
      ErrorCode.NOT_FOUND,
      id ? `${resource} with id ${id} not found` : `${resource} not found`,
      404,
      { resource, id }
    ),
    
  unauthenticated: (message?: string) =>
    new AppError(ErrorCode.UNAUTHENTICATED, message, 401),
    
  forbidden: (message?: string) =>
    new AppError(ErrorCode.FORBIDDEN, message, 403),
    
  database: (message?: string, cause?: unknown) =>
    new AppError(ErrorCode.DATABASE_ERROR, message, 500, { cause }),
    
  internal: (message?: string, cause?: unknown) =>
    new AppError(ErrorCode.INTERNAL_ERROR, message, 500, { cause }),
};

// ============================================================================
// CONVERSION UTILITIES (layer boundaries)
// ============================================================================

export function toTrpcError(error: unknown) {
  if (error instanceof AppError) {
    const codeMap: Record<number, string> = {
      400: 'BAD_REQUEST',
      401: 'UNAUTHORIZED',
      403: 'FORBIDDEN',
      404: 'NOT_FOUND',
      500: 'INTERNAL_SERVER_ERROR',
    };
    
    return {
      code: codeMap[error.statusCode] || 'INTERNAL_SERVER_ERROR',
      message: error.message,
      cause: error,
    };
  }
  
  return {
    code: 'INTERNAL_SERVER_ERROR',
    message: 'An unexpected error occurred',
    cause: error,
  };
}

export function toHttpError(error: unknown) {
  if (error instanceof AppError) {
    return {
      status: error.statusCode,
      body: {
        error: error.code,
        message: error.message,
        ...(error.context && { details: error.context }),
      },
    };
  }
  
  return {
    status: 500,
    body: {
      error: ErrorCode.INTERNAL_ERROR,
      message: ErrorMessage.INTERNAL_ERROR,
    },
  };
}

export function toUserMessage(error: unknown): string {
  if (error instanceof AppError) {
    // User-friendly messages
    if (error.statusCode >= 500) {
      return 'Something went wrong. Please try again.';
    }
    return error.message;
  }
  
  return 'An unexpected error occurred';
}
