/**
 * @generated by @app/core:setup
 * @generatedAt 2024-01-15T10:00:00Z
 * 
 * Centralized error handler - Single point for all error handling
 */

import { createFileMetadata } from '@app/tools/file-marker/marker';
import { logger } from '@app/logger';
import { BaseError } from './base';

export const __metadata = createFileMetadata('@app/core:setup');

/**
 * Error handler result
 */
export interface ErrorHandlerResult {
  code: string;
  message: string;
  statusCode: number;
  details?: unknown;
  stack?: string;
}

/**
 * Handle any error and return standardized result
 * All errors should flow through this function
 */
export function handleError(error: unknown): ErrorHandlerResult {
  // Known operational errors
  if (error instanceof BaseError) {
    logger.error(error.message, {
      code: error.code,
      statusCode: error.statusCode,
      context: error.context,
      stack: error.stack,
    });

    return {
      code: error.code,
      message: error.message,
      statusCode: error.statusCode,
      details: error.context,
      ...(process.env.NODE_ENV === 'development' && { stack: error.stack }),
    };
  }

  // Unknown errors (programmer errors)
  if (error instanceof Error) {
    logger.error('Unexpected error', {
      message: error.message,
      stack: error.stack,
    });

    return {
      code: 'INTERNAL_SERVER_ERROR',
      message:
        process.env.NODE_ENV === 'production'
          ? 'An unexpected error occurred'
          : error.message,
      statusCode: 500,
      ...(process.env.NODE_ENV === 'development' && { stack: error.stack }),
    };
  }

  // Non-Error objects
  logger.error('Unknown error type', { error });

  return {
    code: 'INTERNAL_SERVER_ERROR',
    message: 'An unexpected error occurred',
    statusCode: 500,
  };
}

/**
 * Async error wrapper for try/catch elimination
 * Use this to wrap async functions
 */
export function catchAsync<T>(
  fn: () => Promise<T>
): Promise<{ success: true; data: T } | { success: false; error: ErrorHandlerResult }> {
  return fn()
    .then((data) => ({ success: true as const, data }))
    .catch((error) => ({ success: false as const, error: handleError(error) }));
}

/**
 * tRPC error handler
 * Converts our errors to tRPC format
 */
export function handleTrpcError(error: unknown) {
  const handled = handleError(error);

  // Map to tRPC error codes
  const trpcCodeMap: Record<number, string> = {
    400: 'BAD_REQUEST',
    401: 'UNAUTHORIZED',
    403: 'FORBIDDEN',
    404: 'NOT_FOUND',
    500: 'INTERNAL_SERVER_ERROR',
  };

  return {
    code: trpcCodeMap[handled.statusCode] || 'INTERNAL_SERVER_ERROR',
    message: handled.message,
    data: {
      code: handled.code,
      details: handled.details,
      ...(handled.stack && { stack: handled.stack }),
    },
  };
}
