/**
 * @generated by @app/core:setup
 * @generatedAt 2024-01-15T10:00:00Z
 * 
 * Error handling utilities - ONE place for error handling logic
 * Each layer imports and uses these utilities at their boundary
 */

import { createFileMetadata } from '@app/tools/file-marker/marker';
import { BaseError } from './base';
import { ValidationError } from './validation-error';
import { NotFoundError } from './not-found-error';
import { DatabaseError } from './database-error';
import { AuthenticationError, AuthorizationError } from './auth-error';

export const __metadata = createFileMetadata('@app/core:setup');

/**
 * Convert domain error to tRPC error
 * USE THIS in your tRPC routers
 */
export function toTrpcError(error: unknown) {
  // Known domain errors
  if (error instanceof ValidationError) {
    return {
      code: 'BAD_REQUEST' as const,
      message: error.message,
      cause: error,
    };
  }

  if (error instanceof NotFoundError) {
    return {
      code: 'NOT_FOUND' as const,
      message: error.message,
      cause: error,
    };
  }

  if (error instanceof AuthenticationError) {
    return {
      code: 'UNAUTHORIZED' as const,
      message: error.message,
      cause: error,
    };
  }

  if (error instanceof AuthorizationError) {
    return {
      code: 'FORBIDDEN' as const,
      message: error.message,
      cause: error,
    };
  }

  if (error instanceof DatabaseError) {
    return {
      code: 'INTERNAL_SERVER_ERROR' as const,
      message: 'An error occurred while processing your request',
      cause: error,
    };
  }

  // Unknown errors
  return {
    code: 'INTERNAL_SERVER_ERROR' as const,
    message: 'An unexpected error occurred',
    cause: error,
  };
}

/**
 * Convert domain error to HTTP response
 * USE THIS in REST API routes
 */
export function toHttpError(error: unknown) {
  if (error instanceof ValidationError) {
    return {
      status: 400,
      body: {
        error: error.code,
        message: error.message,
        details: error.context,
      },
    };
  }

  if (error instanceof NotFoundError) {
    return {
      status: 404,
      body: {
        error: error.code,
        message: error.message,
      },
    };
  }

  if (error instanceof AuthenticationError) {
    return {
      status: 401,
      body: {
        error: error.code,
        message: error.message,
      },
    };
  }

  if (error instanceof AuthorizationError) {
    return {
      status: 403,
      body: {
        error: error.code,
        message: error.message,
      },
    };
  }

  if (error instanceof DatabaseError) {
    return {
      status: 500,
      body: {
        error: 'INTERNAL_SERVER_ERROR',
        message: 'An error occurred',
      },
    };
  }

  // Unknown error
  return {
    status: 500,
    body: {
      error: 'INTERNAL_SERVER_ERROR',
      message: 'An unexpected error occurred',
    },
  };
}

/**
 * Convert domain error to user-friendly message
 * USE THIS in UI components
 */
export function toUserMessage(error: unknown): string {
  if (error instanceof ValidationError) {
    return error.message;
  }

  if (error instanceof NotFoundError) {
    return `${error.message}`;
  }

  if (error instanceof AuthenticationError) {
    return 'Please log in to continue';
  }

  if (error instanceof AuthorizationError) {
    return 'You do not have permission to perform this action';
  }

  if (error instanceof DatabaseError) {
    return 'Something went wrong. Please try again.';
  }

  return 'An unexpected error occurred';
}

/**
 * Check if error should be logged
 */
export function shouldLog(error: unknown): boolean {
  // Don't log expected errors
  if (error instanceof ValidationError) return false;
  if (error instanceof NotFoundError) return false;
  
  // Log unexpected errors
  return true;
}

/**
 * Check if error should be reported to monitoring (Sentry, etc)
 */
export function shouldReport(error: unknown): boolean {
  // Only report unexpected errors
  if (error instanceof BaseError && error.isOperational) {
    return false; // Expected errors
  }
  
  return true; // Unexpected errors
}
