/**
 * @generated by @app/core:setup
 * @generatedAt 2024-01-15T10:00:00Z
 * 
 * React Error Boundary - Catches React render errors
 */

import { createFileMetadata } from '@app/tools/file-marker/marker';
import { Component, type ReactNode } from 'react';
import { logger } from '@app/logger';
import { handleError } from './error-handler';

export const __metadata = createFileMetadata('@app/core:setup');

interface Props {
  children: ReactNode;
  fallback?: (error: Error, reset: () => void) => ReactNode;
}

interface State {
  hasError: boolean;
  error: Error | null;
}

/**
 * Error Boundary component
 * Wrap your app or routes with this
 */
export class ErrorBoundary extends Component<Props, State> {
  constructor(props: Props) {
    super(props);
    this.state = { hasError: false, error: null };
  }

  static getDerivedStateFromError(error: Error): State {
    return { hasError: true, error };
  }

  componentDidCatch(error: Error, errorInfo: { componentStack: string }): void {
    handleError(error);
    logger.error('React Error Boundary caught error', {
      error: error.message,
      componentStack: errorInfo.componentStack,
    });
  }

  reset = (): void => {
    this.setState({ hasError: false, error: null });
  };

  render(): ReactNode {
    if (this.state.hasError && this.state.error) {
      if (this.props.fallback) {
        return this.props.fallback(this.state.error, this.reset);
      }

      return (
        <div style={{ padding: '2rem', maxWidth: '600px', margin: '0 auto' }}>
          <h1>Something went wrong</h1>
          <p>{this.state.error.message}</p>
          <button onClick={this.reset} type="button">
            Try again
          </button>
        </div>
      );
    }

    return this.props.children;
  }
}
