/**
 * @generated by @app/core:setup
 * @generatedAt 2024-01-15T10:00:00Z
 * 
 * Errors package - ONE file, everything exported
 */

import { createFileMetadata } from '@app/tools/file-marker/marker';

export const __metadata = createFileMetadata('@app/core:setup');

// Export everything from the one error file
export {
  ErrorCode,
  ErrorMessage,
  AppError,
  createError,
  toTrpcError,
  toHttpError,
  toUserMessage,
} from './errors';

export type { ErrorCode as ErrorCodeType } from './errors';
