/**
 * @generated by @app/core:setup
 * @generatedAt 2024-01-15T10:00:00Z
 * 
 * Branded types - Maximum type safety
 * Prevents mixing up primitive types
 */

import { createFileMetadata, FILE_MARKER } from '../../../tools/file-marker/marker';

export const __metadata = createFileMetadata('@app/core:setup');

/**
 * Brand utility type
 * Creates a nominal type from a structural type
 */
export type Brand<T, TBrand extends string> = T & { readonly __brand: TBrand };

/**
 * ID Types - Cannot be mixed up
 */
export type UserId = Brand<string, 'UserId'>;
export type PostId = Brand<string, 'PostId'>;
export type CommentId = Brand<string, 'CommentId'>;
export type OrderId = Brand<string, 'OrderId'>;
export type ProductId = Brand<string, 'ProductId'>;

/** ID constructor functions */
export const UserId = (id: string): UserId => id as UserId;
export const PostId = (id: string): PostId => id as PostId;
export const CommentId = (id: string): CommentId => id as CommentId;
export const OrderId = (id: string): OrderId => id as OrderId;
export const ProductId = (id: string): ProductId => id as ProductId;

/**
 * Validation State - Phantom type
 * Ensures data is validated before use
 */
export type Validated<T> = Brand<T, 'Validated'>;
export type Unvalidated<T> = T;

/**
 * Log Level - Branded enum
 * Cannot use plain string
 */
export type LogLevel = Brand<'error' | 'warn' | 'info' | 'debug', 'LogLevel'>;

export const LogLevel = {
  ERROR: 'error' as LogLevel,
  WARN: 'warn' as LogLevel,
  INFO: 'info' as LogLevel,
  DEBUG: 'debug' as LogLevel,
} as const;

/**
 * File Paths - Template literal branding
 * Enforces naming conventions
 */
export type RouterPath = Brand<string, 'RouterPath'> & `${string}.router`;
export type SchemaPath = Brand<string, 'SchemaPath'> & `${string}.schema`;
export type ServicePath = Brand<string, 'ServicePath'> & `${string}.service`;
export type EntityPath = Brand<string, 'EntityPath'> & `${string}.entity`;

/**
 * Email - Branded string
 * Ensures email validation
 */
export type Email = Brand<string, 'Email'>;
export const Email = (email: string): Email => {
  // Basic validation
  if (!email.includes('@')) {
    throw new Error('Invalid email format');
  }
  return email as Email;
};

/**
 * URL - Branded string
 * Ensures URL validation
 */
export type Url = Brand<string, 'Url'>;
export const Url = (url: string): Url => {
  try {
    new URL(url);
    return url as Url;
  } catch {
    throw new Error('Invalid URL format');
  }
};

/**
 * NonEmptyString - Cannot be empty
 */
export type NonEmptyString = Brand<string, 'NonEmptyString'>;
export const NonEmptyString = (str: string): NonEmptyString => {
  if (str.length === 0) {
    throw new Error('String cannot be empty');
  }
  return str as NonEmptyString;
};

/**
 * PositiveNumber - Must be positive
 */
export type PositiveNumber = Brand<number, 'PositiveNumber'>;
export const PositiveNumber = (num: number): PositiveNumber => {
  if (num <= 0) {
    throw new Error('Number must be positive');
  }
  return num as PositiveNumber;
};
