/**
 * @generated by @app/core:setup
 * @generatedAt 2024-01-15T10:00:00Z
 * 
 * Pagination types - Standard across all APIs
 */

import { createFileMetadata } from '../../../tools/file-marker/marker';

export const __metadata = createFileMetadata('@app/core:setup');

/**
 * Cursor-based pagination
 * Best for infinite scroll, real-time data
 */
export interface CursorPaginationInput {
  cursor?: string | null;
  limit?: number;
}

export interface CursorPaginatedResponse<T> {
  data: T[];
  nextCursor: string | null;
  hasMore: boolean;
}

/**
 * Offset-based pagination
 * Best for traditional page numbers
 */
export interface OffsetPaginationInput {
  page?: number;
  limit?: number;
}

export interface OffsetPaginatedResponse<T> {
  data: T[];
  pagination: {
    page: number;
    limit: number;
    total: number;
    totalPages: number;
  };
}

/**
 * Sort options
 */
export type SortDirection = 'asc' | 'desc';

export interface SortOption<T = string> {
  field: T;
  direction: SortDirection;
}
