/**
 * @generated by @app/core:setup
 * @generatedAt 2024-01-15T10:00:00Z
 * 
 * Database error - DB operation failures
 */

import { createFileMetadata } from '@app/tools/file-marker/marker';
import { BaseError } from './base';

export const __metadata = createFileMetadata('@app/core:setup');

export class DatabaseError extends BaseError {
  constructor(message: string, context?: Record<string, unknown>) {
    super(message, 'DATABASE_ERROR', 500, true, context);
  }
}
