/**
 * @generated by @app/core:setup
 * @generatedAt 2024-01-15T10:00:00Z
 * 
 * Errors package - Centralized error handling
 */

import { createFileMetadata } from '../../../tools/file-marker/marker';

export const __metadata = createFileMetadata('@app/core:setup');

export { BaseError } from './base';
export { ValidationError } from './validation-error';
export { DatabaseError } from './database-error';
export { NotFoundError } from './not-found-error';
export { AuthenticationError, AuthorizationError } from './auth-error';
