/**
 * @generated by @app/core:setup
 * @generatedAt 2024-01-15T10:00:00Z
 * 
 * Not found error - Resource not found
 */

import { createFileMetadata } from '@app/tools/file-marker/marker';
import { BaseError } from './base';

export const __metadata = createFileMetadata('@app/core:setup');

export class NotFoundError extends BaseError {
  constructor(resource: string, id?: string) {
    const message = id
      ? `${resource} with id ${id} not found`
      : `${resource} not found`;
    super(message, 'NOT_FOUND', 404, true, { resource, id });
  }
}
