/**
 * @generated by @app/core:setup
 * @generatedAt 2024-01-15T10:00:00Z
 * 
 * Validation error - Data validation failures
 */

import { createFileMetadata } from '@app/tools/file-marker/marker';
import { BaseError } from './base';

export const __metadata = createFileMetadata('@app/core:setup');

export class ValidationError extends BaseError {
  constructor(message: string, context?: Record<string, unknown>) {
    super(message, 'VALIDATION_ERROR', 400, true, context);
  }
}
