/**
 * @generated by @app/core:setup
 * @generatedAt 2024-01-15T10:00:00Z
 * 
 * Database client - SINGLE PRISMA INSTANCE
 * DO NOT create PrismaClient anywhere else
 */

import { createFileMetadata } from '../../../tools/file-marker/marker';
import { PrismaClient } from '@prisma/client';
import { logger } from '@app/logger';

export const __metadata = createFileMetadata('@app/core:setup');

// Singleton instance
const prismaClientSingleton = () => {
  const client = new PrismaClient({
    log:
      process.env.NODE_ENV === 'development'
        ? ['query', 'error', 'warn']
        : ['error'],
  });

  logger.info('Prisma client initialized');

  return client;
};

declare global {
  // eslint-disable-next-line no-var
  var prisma: undefined | ReturnType<typeof prismaClientSingleton>;
}

const prisma = globalThis.prisma ?? prismaClientSingleton();

if (process.env.NODE_ENV !== 'production') {
  globalThis.prisma = prisma;
}

// Export as `db` - the ONLY way to access database
export const db = prisma;

// For cleanup
export async function disconnectDatabase() {
  await prisma.$disconnect();
  logger.info('Prisma client disconnected');
}
