/**
 * @generated by @app/core:setup
 * @generatedAt 2024-01-15T10:00:00Z
 * 
 * Database package - Centralized database access
 * 
 * ✅ CORRECT: import { db } from '@app/database';
 * ❌ WRONG: import { PrismaClient } from '@prisma/client'; new PrismaClient()
 */

import { createFileMetadata } from '../../../tools/file-marker/marker';

export const __metadata = createFileMetadata('@app/core:setup');

export { db, disconnectDatabase } from './client';
export { cursorPaginate, offsetPaginate } from './pagination';

// Re-export Prisma types (but not PrismaClient)
export type { Prisma } from '@prisma/client';
