/**
 * @generated by @app/core:setup
 * @generatedAt 2024-01-15T10:00:00Z
 * 
 * Config package - Environment & constants
 */

import { createFileMetadata } from '@app/tools/file-marker/marker';

export const __metadata = createFileMetadata('@app/core:setup');

export { env } from './env';
export * from './constants';
