/**
 * Feature Generator Template
 * Generates COMPLETE feature with:
 * - Domain layer (service + repository)
 * - API layer (tRPC router)
 * - Validation schemas
 * - Unit tests (mocked)
 * - Integration tests (real DB)
 */

import type { FeatureConfig } from '../types';

export function generateFeature(config: FeatureConfig) {
  const { name, fields, operations } = config;
  const timestamp = new Date().toISOString();

  return {
    // 1. Domain Service
    service: generateService(name, fields, operations, timestamp),
    
    // 2. Domain Repository
    repository: generateRepository(name, fields, timestamp),
    
    // 3. Validation Schemas
    schemas: generateSchemas(name, fields, timestamp),
    
    // 4. tRPC Router
    router: generateRouter(name, operations, timestamp),
    
    // 5. Unit Tests (Mocked)
    serviceTests: generateServiceTests(name, operations, timestamp),
    
    // 6. Integration Tests (Real DB)
    integrationTests: generateIntegrationTests(name, operations, timestamp),
  };
}

function generateService(
  name: string,
  fields: FeatureConfig['fields'],
  operations: FeatureConfig['operations'],
  timestamp: string
): string {
  const capitalized = capitalize(name);
  const hasCreate = operations.includes('create');
  const hasUpdate = operations.includes('update');
  const hasDelete = operations.includes('delete');
  const hasList = operations.includes('list');
  const hasGet = operations.includes('get');

  return `/**
 * @generated by @app/generators:feature
 * @generatedAt ${timestamp}
 * 
 * ${capitalized} Service - Business logic layer (Clean Code DI)
 */

import { createFileMetadata } from '@app/tools/file-marker/marker';
import type { ILogger } from '@app/logger';
import { createError } from '@app/errors';
import type { ${capitalized}, ${capitalized}Id, Validated } from '@app/types';
import type { ${capitalized}Repository } from './${name}.repository';
import type { Create${capitalized}Input, Update${capitalized}Input } from '@app/validation';

export const __metadata = createFileMetadata('@app/generators:feature');

export class ${capitalized}Service {
  constructor(
    private readonly logger: ILogger,
    private readonly repository: ${capitalized}Repository
  ) {}

${hasCreate ? `
  async create(data: Validated<Create${capitalized}Input>): Promise<${capitalized}> {
    this.logger.info('Creating ${name}', { data });

    try {
      const ${name} = await this.repository.create(data);
      this.logger.info('${capitalized} created', { id: ${name}.id });
      return ${name};
    } catch (error) {
      this.logger.error('Failed to create ${name}', error);
      throw createError.database('Failed to create ${name}', error);
    }
  }
` : ''}
${hasGet ? `
  async getById(id: ${capitalized}Id): Promise<${capitalized}> {
    const ${name} = await this.repository.findById(id);

    if (!${name}) {
      throw createError.notFound('${capitalized}', id);
    }

    return ${name};
  }
` : ''}
${hasList ? `
  async list(filters?: Record<string, unknown>): Promise<${capitalized}[]> {
    try {
      return await this.repository.findMany(filters);
    } catch (error) {
      this.logger.error('Failed to list ${name}s', error);
      throw createError.database('Failed to list ${name}s', error);
    }
  }
` : ''}
${hasUpdate ? `
  async update(
    id: ${capitalized}Id,
    data: Validated<Update${capitalized}Input>
  ): Promise<${capitalized}> {
    this.logger.info('Updating ${name}', { id });

    // Verify exists (throws NotFoundError if not)
    await this.getById(id);

    try {
      const updated = await this.repository.update(id, data);
      this.logger.info('${capitalized} updated', { id });
      return updated;
    } catch (error) {
      this.logger.error('Failed to update ${name}', error);
      throw createError.database('Failed to update ${name}', error);
    }
  }
` : ''}
${hasDelete ? `
  async delete(id: ${capitalized}Id): Promise<void> {
    this.logger.info('Deleting ${name}', { id });

    // Verify exists (throws NotFoundError if not)
    await this.getById(id);

    try {
      await this.repository.delete(id);
      this.logger.info('${capitalized} deleted', { id });
    } catch (error) {
      this.logger.error('Failed to delete ${name}', error);
      throw createError.database('Failed to delete ${name}', error);
    }
  }
` : ''}
}
`;
}

function generateRepository(
  name: string,
  fields: FeatureConfig['fields'],
  timestamp: string
): string {
  const capitalized = capitalize(name);

  return `/**
 * @generated by @app/generators:feature
 * @generatedAt ${timestamp}
 * 
 * ${capitalized} Repository - Data access layer
 */

import { createFileMetadata } from '@app/tools/file-marker/marker';
import { db } from '@app/database';
import type { ${capitalized}, ${capitalized}Id } from '@app/types';

export const __metadata = createFileMetadata('@app/generators:feature');

export class ${capitalized}Repository {
  async create(data: Omit<${capitalized}, 'id' | 'createdAt' | 'updatedAt'>): Promise<${capitalized}> {
    return db.${name}.create({ data });
  }

  async findById(id: ${capitalized}Id): Promise<${capitalized} | null> {
    return db.${name}.findUnique({ where: { id } });
  }

  async findMany(filters?: Record<string, unknown>): Promise<${capitalized}[]> {
    return db.${name}.findMany({ where: filters });
  }

  async update(
    id: ${capitalized}Id,
    data: Partial<Omit<${capitalized}, 'id' | 'createdAt' | 'updatedAt'>>
  ): Promise<${capitalized}> {
    return db.${name}.update({ where: { id }, data });
  }

  async delete(id: ${capitalized}Id): Promise<void> {
    await db.${name}.delete({ where: { id } });
  }
}
`;
}

function generateSchemas(
  name: string,
  fields: FeatureConfig['fields'],
  timestamp: string
): string {
  const capitalized = capitalize(name);
  
  const fieldSchemas = fields
    .map((f) => `  ${f.name}: ${getZodType(f.type)}${f.required ? '' : '.optional()'},`)
    .join('\n');

  return `/**
 * @generated by @app/generators:feature
 * @generatedAt ${timestamp}
 * 
 * ${capitalized} Validation Schemas
 */

import { createFileMetadata } from '@app/tools/file-marker/marker';
import { z } from 'zod';
import { common } from './common.schema';

export const __metadata = createFileMetadata('@app/generators:feature');

export const create${capitalized}Schema = z.object({
${fieldSchemas}
});

export const update${capitalized}Schema = create${capitalized}Schema.partial();

export const ${name}IdSchema = common.id;

export type Create${capitalized}Input = z.infer<typeof create${capitalized}Schema>;
export type Update${capitalized}Input = z.infer<typeof update${capitalized}Schema>;
`;
}

function generateRouter(
  name: string,
  operations: FeatureConfig['operations'],
  timestamp: string
): string {
  const capitalized = capitalize(name);
  const hasCreate = operations.includes('create');
  const hasGet = operations.includes('get');
  const hasList = operations.includes('list');
  const hasUpdate = operations.includes('update');
  const hasDelete = operations.includes('delete');

  return `/**
 * @generated by @app/generators:feature
 * @generatedAt ${timestamp}
 * 
 * ${capitalized} tRPC Router
 */

import { createFileMetadata } from '../../../../tools/file-marker/marker';
import { router, publicProcedure } from '../trpc';
import { validate } from '@app/validation';
import { handleTrpcError } from '@app/errors';
import { ${capitalized}Service } from '@app/domain/${name}';
import { create${capitalized}Schema, update${capitalized}Schema, ${name}IdSchema } from '@app/validation';

export const __metadata = createFileMetadata('@app/generators:feature');

const service = new ${capitalized}Service();

export const ${name}Router = router({
${hasCreate ? `
  create: publicProcedure
    .input(create${capitalized}Schema)
    .mutation(async ({ input, ctx }) => {
      try {
        const validated = validate(create${capitalized}Schema, input);
        return await ctx.${name}Service.create(validated);
      } catch (error) {
        // ONE utility converts all domain errors
        throw new TRPCError(toTrpcError(error));
      }
    }),
` : ''}
${hasGet ? `
  getById: publicProcedure
    .input(${name}IdSchema)
    .query(async ({ input, ctx }) => {
      try {
        return await ctx.${name}Service.getById(input);
      } catch (error) {
        throw new TRPCError(toTrpcError(error));
      }
    }),
` : ''}
${hasList ? `
  list: publicProcedure
    .query(async ({ ctx }) => {
      try {
        return await ctx.${name}Service.list();
      } catch (error) {
        throw new TRPCError(toTrpcError(error));
      }
    }),
` : ''}
${hasUpdate ? `
  update: publicProcedure
    .input(z.object({
      id: ${name}IdSchema,
      data: update${capitalized}Schema,
    }))
    .mutation(async ({ input, ctx }) => {
      try {
        const validated = validate(update${capitalized}Schema, input.data);
        return await ctx.${name}Service.update(input.id, validated);
      } catch (error) {
        throw new TRPCError(toTrpcError(error));
      }
    }),
` : ''}
${hasDelete ? `
  delete: publicProcedure
    .input(${name}IdSchema)
    .mutation(async ({ input, ctx }) => {
      try {
        await ctx.${name}Service.delete(input);
        return { success: true };
      } catch (error) {
        throw new TRPCError(toTrpcError(error));
      }
    }),
` : ''}
});
`;
}

function generateServiceTests(
  name: string,
  operations: FeatureConfig['operations'],
  timestamp: string
): string {
  const capitalized = capitalize(name);

  return `/**
 * @generated by @app/generators:feature
 * @generatedAt ${timestamp}
 * 
 * ${capitalized} Service Tests - Unit tests with mocks
 */

import { describe, it, expect, vi, beforeEach } from 'vitest';
import { ${capitalized}Service } from './${name}.service';
import type { ${capitalized}Repository } from './${name}.repository';
import type { ILogger } from '@app/logger';
import { AppError } from '@app/errors';

describe('${capitalized}Service', () => {
  let service: ${capitalized}Service;
  let mockLogger: ILogger;
  let mockRepository: ${capitalized}Repository;

  beforeEach(() => {
    mockLogger = {
      info: vi.fn(),
      error: vi.fn(),
      warn: vi.fn(),
      debug: vi.fn(),
    } as unknown as ILogger;

    mockRepository = {
      create: vi.fn(),
      findById: vi.fn(),
      findMany: vi.fn(),
      update: vi.fn(),
      delete: vi.fn(),
    } as unknown as ${capitalized}Repository;

    service = new ${capitalized}Service(mockLogger, mockRepository);
  });

${operations.includes('create') ? `
  describe('create', () => {
    it('should create ${name} successfully', async () => {
      const input = { /* mock data */ };
      const expected = { id: '1', ...input };

      vi.mocked(mockRepository.create).mockResolvedValue(expected);

      const result = await service.create(input as any);

      expect(result).toEqual(expected);
      expect(mockRepository.create).toHaveBeenCalledWith(input);
      expect(mockLogger.info).toHaveBeenCalledWith('Creating ${name}', expect.any(Object));
    });

    it('should throw AppError on repository failure', async () => {
      const input = { /* mock data */ };
      vi.mocked(mockRepository.create).mockRejectedValue(new Error('DB error'));

      await expect(service.create(input as any)).rejects.toThrow(AppError);
      expect(mockLogger.error).toHaveBeenCalled();
    });
  });
` : ''}
${operations.includes('get') ? `
  describe('getById', () => {
    it('should return ${name} when found', async () => {
      const expected = { id: '1', /* mock data */ };
      vi.mocked(mockRepository.findById).mockResolvedValue(expected as any);

      const result = await service.getById('1' as any);

      expect(result).toEqual(expected);
    });

    it('should throw AppError when not found', async () => {
      vi.mocked(mockRepository.findById).mockResolvedValue(null);

      await expect(service.getById('1' as any)).rejects.toThrow(AppError);
    });
  });
` : ''}
});
`;
}

function generateIntegrationTests(
  name: string,
  operations: FeatureConfig['operations'],
  timestamp: string
): string {
  const capitalized = capitalize(name);

  return `/**
 * @generated by @app/generators:feature
 * @generatedAt ${timestamp}
 * 
 * ${capitalized} Integration Tests - Real DB tests
 */

import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import { db } from '@app/database';
import { ${capitalized}Service } from './${name}.service';
import { ${capitalized}Repository } from './${name}.repository';

describe('${capitalized} Integration', () => {
  let service: ${capitalized}Service;
  let repository: ${capitalized}Repository;

  beforeAll(async () => {
    repository = new ${capitalized}Repository();
    service = new ${capitalized}Service(repository);
  });

  afterAll(async () => {
    // Cleanup test data
    await db.${name}.deleteMany({});
  });

${operations.includes('create') && operations.includes('get') ? `
  it('should create and retrieve ${name}', async () => {
    const input = { /* mock data */ };
    
    const created = await service.create(input as any);
    expect(created.id).toBeDefined();

    const retrieved = await service.getById(created.id);
    expect(retrieved).toEqual(created);
  });
` : ''}
${operations.includes('create') && operations.includes('update') ? `
  it('should update ${name}', async () => {
    const input = { /* mock data */ };
    const created = await service.create(input as any);

    const updateData = { /* updated data */ };
    const updated = await service.update(created.id, updateData as any);

    expect(updated.id).toEqual(created.id);
    // Add more assertions
  });
` : ''}
${operations.includes('delete') ? `
  it('should delete ${name}', async () => {
    const input = { /* mock data */ };
    const created = await service.create(input as any);

    await service.delete(created.id);

    await expect(service.getById(created.id)).rejects.toThrow();
  });
` : ''}
});
`;
}

// Helper functions
function capitalize(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

function getZodType(type: string): string {
  const typeMap: Record<string, string> = {
    string: 'z.string()',
    number: 'z.number()',
    boolean: 'z.boolean()',
    date: 'z.date()',
    email: 'common.email',
    url: 'common.url',
  };
  return typeMap[type] || 'z.string()';
}
